package com.daview.app.player

import android.media.AudioFocusRequest
import android.media.AudioManager
import android.net.Uri
import android.os.SystemClock
import android.view.View
import android.view.ViewGroup
import androidx.activity.compose.setContent
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.lifecycle.Lifecycle
import androidx.media3.common.Player
import androidx.media3.common.util.UnstableApi
import androidx.media3.ui.PlayerView
import androidx.test.core.app.ActivityScenario
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.daview.app.MainActivity
import com.daview.app.ui.InternalPlayer
import com.daview.app.ui.PipRequest
import com.daview.app.ui.PlayerScreenState
import com.daview.shared.model.ItemKind
import com.daview.shared.model.MediaItemDto
import com.daview.shared.model.PlaybackInfoDto
import org.junit.After
import org.junit.Assert.*
import org.junit.Assume.assumeTrue
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.UUID
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicInteger
import java.util.concurrent.atomic.AtomicLong

/** Real player and Activity callbacks, using silent PCM generated by this test. */
@RunWith(AndroidJUnit4::class)
@androidx.annotation.OptIn(UnstableApi::class)
class PlaybackLifecycleOnDeviceTest {
    private val instrumentation = InstrumentationRegistry.getInstrumentation()
    private val media = File(instrumentation.targetContext.cacheDir, "lifecycle-${UUID.randomUUID()}.wav")
    private var scenario: ActivityScenario<MainActivity>? = null
    private lateinit var activity: MainActivity
    private lateinit var player: Player
    private val closed = CountDownLatch(1)
    private val closeCount = AtomicInteger()
    private val closePosition = AtomicLong(-1)

    @After
    fun cleanUp() {
        scenario?.close()
        media.delete()
    }

    @Test
    fun stoppedActivityPausesAndDisposalReportsTheFinalPositionOnce() {
        startPlayer()
        scenario!!.moveToState(Lifecycle.State.CREATED)
        await("player paused after ON_STOP") { !player.playWhenReady && !player.isPlaying }
        val stoppedAt = onMain { player.currentPosition }
        assertTrue(stoppedAt > 0)

        scenario!!.moveToState(Lifecycle.State.RESUMED)
        assertFalse("Returning to the app must not undo the stopped state", onMain { player.playWhenReady })
        onMain { player.play() }
        await("resumed progress") { player.isPlaying && player.currentPosition > stoppedAt + 200 }
        val beforeClose = onMain { player.currentPosition }
        onMain { activity.setContent { Text("Playback test closed") } }
        assertTrue("onClose was not delivered", closed.await(10, TimeUnit.SECONDS))
        instrumentation.waitForIdleSync()
        assertEquals(1, closeCount.get())
        assertTrue(closePosition.get() >= beforeClose)
        assertFalse(onMain { PipRequest.wanted })
        assertFalse(onMain { PipRequest.enter(activity) })
    }

    @Test
    fun transientAudioFocusLossSuppressesPlaybackAndFocusReturnResumesIt() {
        startPlayer()
        val manager = activity.getSystemService(AudioManager::class.java)
        val request = AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN_TRANSIENT)
            .setAudioAttributes(android.media.AudioAttributes.Builder()
                .setUsage(android.media.AudioAttributes.USAGE_VOICE_COMMUNICATION)
                .setContentType(android.media.AudioAttributes.CONTENT_TYPE_SPEECH)
                .build())
            .setOnAudioFocusChangeListener { }
            .build()
        try {
            assertEquals(AudioManager.AUDIOFOCUS_REQUEST_GRANTED, onMain { manager.requestAudioFocus(request) })
            await("audio focus loss") {
                !player.isPlaying && player.playbackSuppressionReason == Player.PLAYBACK_SUPPRESSION_REASON_TRANSIENT_AUDIO_FOCUS_LOSS
            }
            onMain { manager.abandonAudioFocusRequest(request) }
            await("audio focus return") { player.isPlaying }
        } finally {
            onMain { manager.abandonAudioFocusRequest(request) }
        }
    }

    @Test
    fun visiblePictureInPictureKeepsProgressAndFinishingItReleasesTheSession() {
        startPlayer()
        assumeTrue("Device has no PiP feature", onMain { PipRequest.supported(activity) })
        assertTrue("The platform rejected PiP", onMain { PipRequest.enter(activity) })
        await("PiP became visible") { activity.isInPictureInPictureMode && player.isPlaying }
        val before = onMain { player.currentPosition }
        await("progress while in PiP") { activity.isInPictureInPictureMode && player.currentPosition > before + 300 }
        onMain { activity.finish() }
        assertTrue("PiP session was not disposed", closed.await(10, TimeUnit.SECONDS))
        instrumentation.waitForIdleSync()
        assertEquals(1, closeCount.get())
        assertTrue(closePosition.get() >= before)
        assertFalse(onMain { PipRequest.wanted })
        assertNull(onMain { PipRequest.aspect })
    }

    private fun startPlayer() {
        writeSilentWave()
        val info = PlaybackInfoDto(
            sessionId = UUID.randomUUID().toString(),
            item = MediaItemDto(id = "lifecycle", libraryId = "test", kind = ItemKind.MOVIE, name = "Lifecycle test"),
            streamUrl = Uri.fromFile(media).toString(),
            startPositionMs = 0
        )
        scenario = ActivityScenario.launch(MainActivity::class.java)
        scenario!!.onActivity { host ->
            activity = host
            host.setContent {
                MaterialTheme {
                    InternalPlayer(
                        info = info,
                        screen = androidx.compose.runtime.remember { PlayerScreenState() },
                        subtitleScale = 1f,
                        onProgress = { _, _, _, _ -> },
                        onClose = { position ->
                            closePosition.set(position)
                            closeCount.incrementAndGet()
                            closed.countDown()
                        },
                        onEnded = {},
                        onSkip = { _, _ -> }
                    )
                }
            }
        }
        await("player view attached") { findPlayer(activity.window.decorView) != null }
        player = onMain { checkNotNull(findPlayer(activity.window.decorView)) }
        onMain { player.volume = 0f }
        await("actual media progress") { player.isPlaying && player.currentPosition >= 300 }
    }

    private fun findPlayer(view: View): Player? {
        if (view is PlayerView) return view.player
        if (view is ViewGroup) for (i in 0 until view.childCount) {
            findPlayer(view.getChildAt(i))?.let { return it }
        }
        return null
    }

    private fun <T> onMain(block: () -> T): T {
        var result: Result<T>? = null
        instrumentation.runOnMainSync { result = runCatching(block) }
        return result!!.getOrThrow()
    }

    private fun await(description: String, condition: () -> Boolean) {
        val deadline = SystemClock.elapsedRealtime() + 10_000
        while (SystemClock.elapsedRealtime() < deadline) {
            if (onMain(condition)) return
            Thread.sleep(50)
        }
        fail("Timed out: $description")
    }

    private fun writeSilentWave() {
        val pcm = ByteArray(8_000 * 2 * 45)
        val header = ByteBuffer.allocate(44).order(ByteOrder.LITTLE_ENDIAN)
            .put("RIFF".toByteArray(Charsets.US_ASCII)).putInt(36 + pcm.size)
            .put("WAVEfmt ".toByteArray(Charsets.US_ASCII)).putInt(16)
            .putShort(1).putShort(1).putInt(8_000).putInt(16_000).putShort(2).putShort(16)
            .put("data".toByteArray(Charsets.US_ASCII)).putInt(pcm.size).array()
        media.outputStream().use { it.write(header); it.write(pcm) }
    }
}
